---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tpm
  namespace: tpm

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scc-priv
  namespace: tpm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scc-priv
subjects:
  - kind: ServiceAccount
    name: tpm

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scc-priv
  namespace: tpm
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpm
  namespace: tpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tpm
  template:
    metadata:
      labels:
        app: tpm
    spec:
      containers:
      - name: tpm
        image: quay.io/mrogers950/tpm:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2322
          protocol: TCP
        - containerPort: 2321
          protocol: TCP
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /hostroot
          name: hostroot
      volumes:
      - name: hostroot
        hostPath:
          path: /
          type: ""
      serviceAccountName: tpm
